apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}-${{values.stage}}-${{parameters.owner}}
  namespace: argocd
spec:
  destination:
    namespace: ${{values.name}}-${{values.stage}}
    server: https://kubernetes.default.svc
  project: ${{parameters.owner}}
  source:
    repoURL: 'https://charts.loft.sh/'
    targetRevision: 0.19.3
    chart: vcluster
    helm:
      values: |
        syncer:
          storage:
            persistence: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
