apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}-${{values.stage}}-vc
  namespace: argocd
spec:
  destination:
    namespace: ${{values.name}}-${{values.stage}}
    server: https://kubernetes.default.svc
  project: clusters
  sources:
  - repoURL: 'https://charts.loft.sh/'
    targetRevision: 0.19.3
    chart: vcluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    #- ServerSideApply=true
    - CreateNamespace=true
